spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ohgood/config-center.git
          username:
          password:
eureka:
  client:
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://admin:123456@localhost:8761/eureka/
server:
  port: 8094

